extends:
  - plugin:astro/recommended
overrides:
  - files:
      - "*.astro"
    parser: astro-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions: .astro
parser: "@typescript-eslint/parser"
plugins:
  - prettier
  - simple-import-sort
rules:
  prettier/prettier:
    - error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
settings:
  import/resolver:
    node:
      extensions:
        - .tsx
